apiVersion: v2
name: workflows-docs
description: A Helm chart for N8N Workflows Documentation Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - n8n
  - workflows
  - documentation
  - automation
home: https://github.com/sahiixx/n8n-workflows-1
sources:
  - https://github.com/sahiixx/n8n-workflows-1
maintainers:
  - name: N8N Workflows Team
    email: support@example.com